'use client'

import { useState, useRef } from 'react'
import { toPng } from 'html-to-image'
import { Copy, Image, Share2, MessageSquare, Check, Download } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface ShareActionsProps {
  content: string
  agentName?: string
  isDebate?: boolean
  panelDiscussion?: Array<{ content: string; agentName?: string }>
  className?: string
}

export function ShareActions({
  content,
  agentName = 'Oscar',
  isDebate = false,
  panelDiscussion,
  className = ''
}: ShareActionsProps) {
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)
  const shareCardRef = useRef<HTMLDivElement>(null)

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  // Share as image
  const handleShareAsImage = async () => {
    if (!shareCardRef.current) return

    setDownloading(true)
    try {
      // Make the hidden share card visible for capture
      shareCardRef.current.style.display = 'block'

      const dataUrl = await toPng(shareCardRef.current, {
        quality: 1,
        pixelRatio: 2,
        backgroundColor: '#ffffff',
      })

      // Hide it again
      shareCardRef.current.style.display = 'none'

      // Download the image
      const link = document.createElement('a')
      link.download = `oscar-${isDebate ? 'debate' : 'response'}-${Date.now()}.png`
      link.href = dataUrl
      link.click()
    } catch (err) {
      console.error('Failed to create image:', err)
    } finally {
      setDownloading(false)
    }
  }

  // Share debate (formats the panel discussion for sharing)
  const handleShareDebate = async () => {
    if (!panelDiscussion || panelDiscussion.length === 0) {
      // Fallback to regular copy if no panel discussion
      handleCopy()
      return
    }

    const debateText = panelDiscussion
      .map((p, i) => `**${p.agentName || `Expert ${i + 1}`}:**\n${p.content}`)
      .join('\n\n---\n\n')

    const fullText = `AI Panel Discussion\n\n${debateText}\n\n---\nGenerated by Oscar - tryoscar.app`

    try {
      await navigator.clipboard.writeText(fullText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy debate:', err)
    }
  }

  // Native share (if available)
  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: isDebate ? 'AI Panel Discussion' : 'Oscar Response',
          text: content,
          url: 'https://tryoscar.app',
        })
      } catch (err) {
        // User cancelled or share failed
        console.log('Share cancelled or failed')
      }
    } else {
      // Fallback to copy
      handleCopy()
    }
  }

  return (
    <>
      {/* Action buttons */}
      <div className={`flex items-center space-x-1 ${className}`}>
        {/* Copy to clipboard */}
        <Button
          variant="ghost"
          size="sm"
          onClick={handleCopy}
          className="h-7 px-2 text-xs text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
          title="Copy to clipboard"
        >
          {copied ? (
            <Check className="h-3.5 w-3.5 text-green-500" />
          ) : (
            <Copy className="h-3.5 w-3.5" />
          )}
          <span className="ml-1">Copy</span>
        </Button>

        {/* Share as image */}
        <Button
          variant="ghost"
          size="sm"
          onClick={handleShareAsImage}
          disabled={downloading}
          className="h-7 px-2 text-xs text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
          title="Save as image"
        >
          {downloading ? (
            <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-neutral-400 border-t-transparent" />
          ) : (
            <Download className="h-3.5 w-3.5" />
          )}
          <span className="ml-1">Image</span>
        </Button>

        {/* Share debate (only show if panel discussion exists) */}
        {panelDiscussion && panelDiscussion.length > 0 && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleShareDebate}
            className="h-7 px-2 text-xs text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
            title="Copy full debate"
          >
            <MessageSquare className="h-3.5 w-3.5" />
            <span className="ml-1">Debate</span>
          </Button>
        )}

        {/* Native share (mobile-friendly) */}
        <Button
          variant="ghost"
          size="sm"
          onClick={handleNativeShare}
          className="h-7 px-2 text-xs text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
          title="Share"
        >
          <Share2 className="h-3.5 w-3.5" />
          <span className="ml-1">Share</span>
        </Button>
      </div>

      {/* Hidden share card for image generation */}
      <div
        ref={shareCardRef}
        style={{ display: 'none', position: 'absolute', left: '-9999px' }}
        className="w-[600px] p-8 bg-white rounded-xl shadow-lg"
      >
        {/* Oscar branding header */}
        <div className="flex items-center space-x-3 mb-6 pb-4 border-b border-neutral-200">
          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
            <span className="text-white font-bold text-lg">O</span>
          </div>
          <div>
            <h3 className="font-bold text-neutral-900">{agentName}</h3>
            <p className="text-sm text-neutral-500">tryoscar.app</p>
          </div>
        </div>

        {/* Content */}
        <div className="text-neutral-800 text-base leading-relaxed whitespace-pre-wrap">
          {content.length > 500 ? content.substring(0, 500) + '...' : content}
        </div>

        {/* Footer */}
        <div className="mt-6 pt-4 border-t border-neutral-200 flex items-center justify-between">
          <span className="text-sm text-neutral-400">
            Generated with Oscar - Your AI Second Brain
          </span>
          <div className="flex items-center space-x-2">
            <div className="w-6 h-6 rounded bg-gradient-to-br from-blue-500 to-purple-600" />
          </div>
        </div>
      </div>
    </>
  )
}
